<?php
/**
 * Copyright © MageKey. All rights reserved.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */

$_storeHelper = $this->helper(\MageKey\StoresFlags\Helper\Store::class);
?>

<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
    <strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Language') ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
            <strong class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                <?php if ($currentFlag = $_storeHelper->getCurrentFlag()): ?>
                <span class="flag-icon flag-icon-<?php echo $currentFlag ?>"></span>
                <?php else: ?>
                <span><?php echo $block->escapeHtml($block->getStoreName()) ?></span>
                <?php endif; ?>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown"
            data-mage-init='{"dropdownDialog":{
                "appendTo":"#switcher-language<?php /* @escapeNotVerified */ echo $id ?> > .options",
                "triggerTarget":"#switcher-language-trigger<?php /* @escapeNotVerified */ echo $id ?>",
                "closeOnMouseLeave": false,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":null}}'>
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if ($_lang->getId() != $block->getCurrentStoreId()): ?>
                    <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option<?php echo ($_lang->getFlag() ? ' has-flag' : '') ?>">
                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
                        <?php if ($_lang->getFlag()): ?>
                        <span class="flag-icon flag-icon-<?php echo $_lang->getFlag() ?>"></span>
                        <?php endif; ?>
                        <?php echo $block->escapeHtml($_lang->getName()) ?>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
